# -*- coding: utf-8 -*-

events_categories = ['museum', 'park', 'restaurants', 'art-centers', 'culture',
               'library', 'books', 'attract', 'gallery', 'bowling', 'cathedrals',
               'billiards', 'monument', 'photo-places', 'informal', 'houses',
               'cafe', 'palace', 'castle', 'health-food', 'anticafe',
               'ice-rink', 'confectioneries', 'bar', 'water-park',
               'slope', 'fitness', 'amusement', 'fastfood', 'vegetarian',
               'gifts', 'bridge', 'homesteads', 'temple', 'square',
               'fountain', 'coffee', 'flea-market', 'diving',
               'karts', 'tea', 'salons', 'climbing-walls', 'church',
               'zoo', 'paintball', 'shooting-ranges', 'monastery',
               'mosque', 'synagogue', 'beaches', 'ozyora', 'rope-park',
               'canteens', 'roof', 'inn', 'pet-store', 'rollerdromes',
               'show-room', 'wind-tunnels', 'stable', 'karaoke',
               'excursions', 'kids', 'theater', 'show', 'party', 'exhibition',
               'concert', 'education', 'romance', 'permanent-exhibitions',
               'circus', 'comedy-club', 'stand-up', 'yoga', 'fashion', 'holiday',
               'evening', 'games', 'festival', 'quest', 'night', 'sport', 'photo',
               'fair', 'cinema', 'concert', 'theater', 'show', 'clubs',
               'kids', 'excursions', 'exhibition', 'sport']